language: python
python:
- "2.6"
- "2.7"
addons:
  apt:
    packages:
    - djvulibre-bin
    - libdjvulibre-dev
    - libxml2-utils
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache
install:
- export PATH="/usr/lib/ccache:$PATH"
- pip install --build build-cython cython
- pip install python-djvulibre
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install --build build-lxml lxml
- pip install pyicu
- pip install html5lib
- pip install --build build-pillow pillow
script:
- nosetests --all --verbose
- xmllint --noout --valid doc/*.xml

# vim:ts=2 sts=2 sw=2 et
