language: python
python:
- "2.6"
- "2.7"
before_install:
- sudo apt-get update
- sudo apt-get install -y libdjvulibre-dev djvulibre-bin
install:
- pip install cython
- pip install python-djvulibre
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then pip install argparse; fi
- pip install lxml
- pip install pyicu
- pip install html5lib
- pip install pillow
script:
- nosetests --all --verbose

# vim:ts=2 sts=2 sw=2 et
