#!/bin/sh

# Copyright © 2009-2019 Jakub Wilk <jwilk@jwilk.net>
# Copyright © 2022-2024 FriedrichFroebel
#
# This file is part of ocrodjvu.
#
# ocrodjvu is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# ocrodjvu is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.

set -e -u
version=${1:?"no version number provided"}
date="$(date -u --rfc-3339=date)"
PS4='$ '
set -x
dch -m -v "$version" -u low -c doc/changelog
export version date
perl -pi -e 's/^__version__ = \047\K[\w.]+/$ENV{version}/' ocrodjvu/version.py
perl -pi -e 's/<!ENTITY version \047\K[\w.]+/$ENV{version}/; s/<date>\K[0-9-]+/$ENV{date}/' doc/*.xml
perl -pi -e 's/djvu2hocr \K[\w.]+/$ENV{version}/' tests/test_djvu2hocr/*.test*
